#:schema node_modules/wrangler/config-schema.json
name = "database"
main = "src/index.ts"
compatibility_date = "2024-06-10"
compatibility_flags = ["nodejs_compat"]

services = [{ binding = "STORAGE", service = "storage" }]

[[d1_databases]]
binding = "DB"
database_name = "retrocode"
database_id = "ead6fd56-3f73-4f15-b87f-3a6791b3aa76"

